version: "3"

networks:
    web:
      driver: "bridge"
    api:
      driver: "bridge"

services: 
    naviapi:
        container_name: "navi_api"
        image: "navi_api"
        build: 
            context: .
            dockerfile: /home/websites/navi/src/api/Dockerfile
        expose: 
            - "5002"
        ports: 
            - "5002:5002"
        networks:
            - api
        environment: 
            ASPNETCORE_URLS: "http://*:5002"
            ASPNETCORE_ENVIRONMENT: "production"